"""
test_email.py — Standalone test for BeautyPulse email + PDF generation.

Bypasses the Agent Framework / LLM layer and calls _generate_pdf and
send_analysis_email directly so you can verify Mailtrap delivery without
running the full pipeline.

Usage:
    python test_email.py                          # uses REPORT_RECIPIENT_EMAILS env var
    python test_email.py you@example.com          # override recipient

Required env vars (same as production):
    MAILTRAP_API_TOKEN
    MAILTRAP_SENDER_EMAIL   (optional, default: noreply@minions.app)
    MAILTRAP_SENDER_NAME    (optional, default: BeautyPulse Analytics)
"""
import json
import os
import sys
from datetime import date
from pathlib import Path
from dotenv import load_dotenv

load_dotenv(override=False)

# ── Sample analysis payload — mirrors the real DataAnalystAgent output schema ─
SAMPLE_ANALYSIS = {
    "username": "test_account",
    "analysis_date": date.today().isoformat(),
    "total_posts_analysed": 12,
    "keynotes_summary": (
        "This is a sample analysis report generated by the BeautyPulse test script. "
        "The account posts primarily about skincare routines, product reviews, and "
        "wellness tips for a predominantly female audience aged 18-34."
    ),
    "sentiment_analysis": {
        "overall": "Positive",
        "score": 0.78,
        "breakdown": {
            "positive_pct": 72.5,
            "neutral_pct": 20.0,
            "negative_pct": 7.5,
        },
        "notable_comments": [
            "Love this serum, my skin has never looked better!",
            "Where can I buy this in Singapore?",
            "Does it work for sensitive skin?",
            "Been using this for 3 months — absolutely glowing!",
            "A bit pricey but worth every cent.",
        ],
    },
    "health_beauty_products": [
        {"product_name": "Hydra-Boost Serum", "brand": "CeraVe", "mention_count": 8, "context": "Daily skincare routine"},
        {"product_name": "SPF 50 Sunscreen", "brand": "Biore", "mention_count": 5, "context": "Morning routine essential"},
        {"product_name": "Retinol Night Cream", "brand": "Olay", "mention_count": 4, "context": "Anti-aging treatment"},
        {"product_name": "Vitamin C Serum", "brand": "The Ordinary", "mention_count": 3, "context": "Brightening routine"},
        {"product_name": "Micellar Water", "brand": "Bioderma", "mention_count": 2, "context": "Makeup removal"},
    ],
    "top_hashtags": [
        {"tag": "skincare", "count": 10},
        {"tag": "beautyroutine", "count": 8},
        {"tag": "glowingskin", "count": 7},
        {"tag": "retinol", "count": 5},
        {"tag": "sunscreen", "count": 5},
        {"tag": "kbeauty", "count": 4},
        {"tag": "selfcare", "count": 4},
        {"tag": "cleanskin", "count": 3},
    ],
    "engagement_insights": (
        "Peak engagement occurs on Tuesday and Thursday evenings (8–10 PM SGT). "
        "Videos and carousel posts receive 2.3x more comments than static images. "
        "Posts featuring before/after comparisons drive the highest save rates."
    ),
    "recommendations": [
        "Post video content on Tuesdays and Thursdays between 8–10 PM SGT to maximise reach.",
        "Feature more before/after skincare transformation content — highest save rate format.",
        "Partner with CeraVe and The Ordinary for sponsored content given high organic mention frequency.",
        "Address price-sensitivity comments with 'value bundle' or discount-code posts.",
        "Introduce a weekly Q&A format to capitalise on the high volume of product questions.",
    ],
}


def _test_pdf_generation(username: str) -> bytes:
    """Generate a sample PDF and optionally save it to disk for inspection."""
    from email_agent import _generate_pdf

    print(f"  Generating PDF for @{username} ...")
    pdf_bytes = _generate_pdf(SAMPLE_ANALYSIS, username)
    print(f"  PDF generated — {len(pdf_bytes):,} bytes")

    out_path = Path("results") / f"test_pdf_{username}.pdf"
    out_path.parent.mkdir(exist_ok=True)
    out_path.write_bytes(pdf_bytes)
    print(f"  PDF saved locally → {out_path}")
    return pdf_bytes


def _test_email_send(recipients: list[str]):
    """Call send_analysis_email directly (no LLM) and verify delivery."""
    from email_agent import send_analysis_email

    print(f"  Sending email to: {', '.join(recipients)} ...")
    result = send_analysis_email(
        analysis_json=json.dumps(SAMPLE_ANALYSIS),
        recipient_emails=",".join(recipients),
        username=SAMPLE_ANALYSIS["username"],
    )
    print(f"  Result: {result}")
    return result


def main():
    # Resolve recipients: CLI arg > env var > error
    if len(sys.argv) > 1:
        recipients = [sys.argv[1].strip()]
    else:
        env_val = os.environ.get("REPORT_RECIPIENT_EMAILS", "")
        recipients = [e.strip() for e in env_val.split(",") if e.strip()]

    if not recipients:
        print(
            "ERROR: No recipient specified.\n"
            "  Usage: python test_email.py you@example.com\n"
            "  Or set REPORT_RECIPIENT_EMAILS in your .env file."
        )
        sys.exit(1)

    if not os.environ.get("MAILTRAP_API_TOKEN"):
        print("ERROR: MAILTRAP_API_TOKEN is not set in environment / .env file.")
        sys.exit(1)

    print("\n=== BeautyPulse Email Test ===\n")

    # Step 1: PDF generation
    print("[1/2] Testing PDF generation")
    try:
        _test_pdf_generation(SAMPLE_ANALYSIS["username"])
        print("  ✅ PDF generation OK\n")
    except Exception as exc:
        print(f"  ❌ PDF generation FAILED: {exc}")
        sys.exit(1)

    # Step 2: Mailtrap send
    print("[2/2] Testing Mailtrap email send")
    try:
        _test_email_send(recipients)
        print("  ✅ Email sent OK\n")
    except Exception as exc:
        print(f"  ❌ Email send FAILED: {exc}")
        sys.exit(1)

    print("=== All tests passed ===")
    print(f"Check your inbox at: {', '.join(recipients)}")


if __name__ == "__main__":
    main()
